# El workflow instalar치 las dependencias de Python, ejecutar치 las pruebas con una sola versi칩n de Python (Python 3.11) y ejecutar치 el bot

name: Host Bot

on:
  workflow_dispatch:
    inputs:
      foward_group:
        description: "Specify: 'trial_group' or 'group'."
        required: true
        default: 'trial_group'

permissions:
  contents: read

jobs:
  build_and_host:
    runs-on: ubuntu-latest
    if: github.ref  == 'refs/heads/test' && (github.event.inputs.foward_group == 'trial_group' || github.event.inputs.foward_group == 'group')
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Host Bot using Python and secrets
        env:
          TOKEN_BOT: ${{ secrets.TOKEN_BOT }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          TRIAL_GROUP_ID: ${{ secrets.TRIAL_GROUP_ID }}
          FORWARD_GROUP: ${{ github.event.inputs.foward_group }}
        run: |
          python run_bot.py
